### ISSUE TITLE
[ virustotal-scan ] The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by king1x32** [nikhilbadyal/ghactions#1]
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by nikhilbadyal** [comment]
We don't [use](https://github.com/search?q=repo%3Anikhilbadyal%2Fghactions+set-output&type=code) set-output in this repo.
